export enum HospitalVisitStatus {

    DRAFT = 'DRAFT',
    SCHEDULED = 'SCHEDULED',
    STARTED = 'STARTED',
    CANCELED = 'CANCELED',
    JUST_REQUIRED_FIELDS_FILLED = 'JUST_REQUIRED_FIELDS_FILLED',
    ALL_FIELDS_FILLED = 'ALL_FIELDS_FILLED',
    ENDED_SUCCESSFULLY = 'ENDED_SUCCESSFULLY'

}
