export enum HospitalVisitStatus {

    DRAFT = 'DRAFT',
    SCHEDULED = 'SCHEDULED',

    STARTED = 'STARTED',

    ACTIVITIES_FILLED_OUT = 'ACTIVITIES_FILLED_OUT',
    ALL_FILLED_OUT = 'ALL_FILLED_OUT',

    CANCELED = 'CANCELED',
    FAILED_BECAUSE_NO_CHILD = 'FAILED_BECAUSE_NO_CHILD',
    FAILED_FOR_OTHER_REASON = 'FAILED_FOR_OTHER_REASON',
    SUCCESSFUL = 'SUCCESSFUL'

}
