export enum BoxStatusChangeReason {
    MISSING = 'MISSING',
    BROKEN = 'BROKEN',
    NEED_REFILL = 'NEED_REFILL',
    NEED_CLEANING = 'NEED_CLEANING',
    CEASED = 'CEASED',
    CORRECTED = 'CORRECTED',
    COMMENT = 'COMMENT'
}
