export const affectedObjectsList: Array<string> = [
    'Afrikai dob',
    'Álmodj velem! játék',
    'Bang',
    'Befőttesgumi',
    'Cellux',
    'Cintányér',
    'Coloring book',
    'Csengettyű',
    'Csipesz-doboz (benne: színes karton, szalag, sablon)',
    'Csótánypóker',
    'Csörgő',
    'Dekorgumi',
    'Dixit',
    'Dobble',
    'Dobókockák',
    'Dúdolós füzet',
    'Egyéb',
    'Facsipeszek',
    'Fekete Péter',
    'Filcanyag',
    'Filctollak, ceruzák (tolltartóban)',
    'Francia kártya (+ zsetonok)',
    'Gemkapocs',
    'Gitár',
    'Golyós dob',
    'Güiro (talán, de nem tudom a pontos nevét, recés facső)',
    'Hegyező',
    'Hímzőfonal',
    'Igen? Nem? Egyik sem! játék',
    'Jenga',
    'Joghurtos doboz',
    'Kasztanyetta',
    'Kesztyűbábok (db)',
    'Kétoldalú ragasztó(szalag)',
    'Krepp-papír doboz (benne: zöld, színes, széthúzható csíkok)',
    'Kupak',
    'Mágnescsík',
    'Magyar kártya',
    'Marokkó/Mikádó (pálcikák)',
    'Méhsejtfigurás tasak (benne: mozgószemek, méhsejtpapír, színes kartonok, sablonok)',
    'Mellény',
    'Mesedoboz',
    'Műanyag kanál',
    'Olló',
    'Pálcikák',
    'Panic lab játék',
    'Rajzszög',
    'Rizs (dobozban)',
    'Rumbatök',
    'Sablonos tasak',
    'Sajtosdoboz',
    'Scoubidou',
    'Stift ragasztó',
    'Szerpentin',
    'Színes kották (mappában)',
    'Színes papír (mindenféle szín)',
    'Szívószál (2 méret)',
    'Tabu játék',
    'Társasjátékos mappa',
    'Toalett tekercs',
    'Triangulum',
    'Tűzőgép',
    'Ukulele',
    'Uno/Solo kártya',
    'Valami fa cucc, van nyele, és ha rázzuk, csúszkál benne egy pálcika, aminek a végén van két golyó :D',
    'Várak és kapitányok játék',
    'Vastagabb fonal',
    'Vastagabb karton',
    'Xilofon (2 ütővel)',
    'Zseníliadrót (zöld)',
];
