export enum Permission {

    canWriteChild = 'canWriteChild',
    canReadChild = 'canReadChild',
    canWriteDepartment = 'canWriteDepartment',
    canReadDepartment = 'canReadDepartment',
    canSearchDepartment = 'canSearchDepartment',
    canWriteDepBox = 'canWriteDepBox',
    canReadDepBox = 'canReadDepBox',
    canCreateVisit = 'canCreateVisit',
    canReadVisit = 'canReadVisit',
    canModifyVisit = 'canModifyVisit',
    canCreateActivity = 'canCreateActivity',
    canReadActivity = 'canReadActivity',
    canCreatePerson = 'canCreatePerson',
    canWriteVisitor = 'canWriteVisitor',
    canWriteCoordinator = 'canWriteCoordinator',
    canWriteAdmin = 'canWriteAdmin',
    canWriteSysAdmin = 'canWriteSysAdmin',
    canWriteSelf = 'canWriteSelf',
    canCreateUser = 'canCreateUser',
    canReadPerson = 'canReadPerson',
    canSearchPerson = 'canSearchPerson',
    canModifyPersonCity = 'canModifyPersonCity',
    canReadSensitivePersonData = 'canReadSensitivePersonData',
    canReadPersonCreateData = 'canReadPersonCreateData',
    canReadUserCreateData = 'canReadUserCreateData',
    canReadUserLastLoginData = 'canReadUserLastLoginData',
    canManagePermissions = 'canManagePermissions',
    canReadStatistics = 'canReadStatistics',

}
