export const affectedObjectsList: Array<string> = [
    'Társasjátékos mappa',
    'Magyar kártya',
    'Francia kártya (+ zsetonok)',
    'Fekete Péter',
    'Uno/Solo kártya',
    'Jenga',
    'Marokkó/Mikádó (pálcikák)',
    'Csótánypóker',
    'Tabu játék',
    'Dixit',
    'Dobble',
    'Bang',
    'Igen? Nem? Egyik sem! játék',
    'Álmodj velem! játék',
    'Panic lab játék',
    'Várak és kapitányok játék',
    'Dobókockák',
    'Krepp-papír doboz (benne: zöld, színes, széthúzható csíkok)',
    'Csipesz-doboz (benne: színes karton, szalag, sablon)',
    'Méhsejtfigurás tasak (benne: mozgószemek, méhsejtpapír, színes kartonok, sablonok)',
    'Sablonos tasak',
    'Olló',
    'Stift ragasztó',
    'Hegyező',
    'Tűzőgép',
    'Cellux',
    'Kétoldalú ragasztó(szalag)',
    'Gemkapocs',
    'Rajzszög',
    'Színes papír (mindenféle szín)',
    'Vastagabb karton',
    'Filcanyag',
    'Dekorgumi',
    'Filctollak, ceruzák (tolltartóban)',
    'Scoubidou',
    'Hímzőfonal',
    'Vastagabb fonal',
    'Szívószál (2 méret)',
    'Pálcikák',
    'Facsipeszek',
    'Zseníliadrót (zöld)',
    'Mágnescsík',
    'Sajtosdoboz',
    'Toalett tekercs',
    'Befőttesgumi',
    'Joghurtos doboz',
    'Műanyag kanál',
    'Kupak',
    'Rizs (dobozban)',
    'Szerpentin',
    'Mesedoboz',
    'Kesztyűbábok (db)',
    'Dúdolós füzet',
    'Színes kották (mappában)',
    'Gitár',
    'Güiro (talán, de nem tudom a pontos nevét, recés facső)',
    'Valami fa cucc, van nyele, és ha rázzuk, csúszkál benne egy pálcika, aminek a végén van két golyó :D',
    'Csengettyű',
    'Csörgő',
    'Golyós dob',
    'Cintányér',
    'Kasztanyetta',
    'Triangulum',
    'Xilofon (2 ütővel)',
    'Rumbatök',
    'Afrikai dob',
    'Ukulele',
    'Coloring book',
    'Mellény',
    'Egyéb'
];
