export enum ApiError {
    VISIT_SAME_TIME_SAME_DEPARTMENT_LIMIT_EXCEEDED ='VISIT_SAME_TIME_SAME_DEPARTMENT_LIMIT_EXCEEDED',
    VOLUNTEER_COULD_PARTICIPANT_ONE_VISIT_AT_SAME_TIME ='VOLUNTEER_COULD_PARTICIPANT_ONE_VISIT_AT_SAME_TIME'
}
