export enum ApiError {
    VISIT_SAME_TIME_SAME_DEPARTMENT_LIMIT_EXCEEDED = 'VISIT_SAME_TIME_SAME_DEPARTMENT_LIMIT_EXCEEDED',
    VOLUNTEER_COULD_PARTICIPANT_ONE_VISIT_AT_SAME_TIME = 'VOLUNTEER_COULD_PARTICIPANT_ONE_VISIT_AT_SAME_TIME',

    USER_CANNOT_CREATE_VISIT = 'USER_CANNOT_CREATE_VISIT',
    USER_CANNOT_CREATE_VISIT_FOR_OTHERS = 'USER_CANNOT_CREATE_VISIT_FOR_OTHERS',
    USER_CANNOT_MODIFY_VISIT = 'USER_CANNOT_MODIFY_VISIT',
    USER_CANNOT_MODIFY_VISIT_FOR_OTHERS = 'USER_CANNOT_MODIFY_VISIT_FOR_OTHERS',

    VISITS_ARE_NOT_IN_SAME_CONNECTION_GROUP = 'VISITS_ARE_NOT_IN_SAME_CONNECTION_GROUP',
    CONNECT_CANDIDATE_ALREADY_IN_GROUP = 'CONNECT_CANDIDATE_ALREADY_IN_GROUP',
    CONNECT_CANDIDATE_IS_MUCH_EARLIER_OR_LATER = 'CONNECT_CANDIDATE_IS_MUCH_EARLIER_OR_LATER',
    VISITS_HAS_NO_COMMON_PARTICIPANTS = 'VISITS_HAS_NO_COMMON_PARTICIPANTS',
    CANNOT_CONNECT_VISITS_TO_ITSELF = 'CANNOT_CONNECT_VISITS_TO_ITSELF',
    CANNOT_MODIFY_DEPARTMENT_OF_CONNECTED_VISIT = 'CANNOT_MODIFY_DEPARTMENT_OF_CONNECTED_VISIT',
    CANNOT_MODIFY_PARTICIPANTS_OF_CONNECTED_VISIT = 'CANNOT_MODIFY_PARTICIPANTS_OF_CONNECTED_VISIT',
    CANNOT_MODIFY_TIME_OF_CONNECTED_VISIT = 'CANNOT_MODIFY_TIME_OF_CONNECTED_VISIT',
    CANNOT_MODIFY_COUNTED_MINUTES_OF_CONNECTED_VISIT = 'CANNOT_MODIFY_COUNTED_MINUTES_OF_CONNECTED_VISIT',
    VICARIOUS_MOM_VISIT_CANNOT_BE_CONNECTED = 'VICARIOUS_MOM_VISIT_CANNOT_BE_CONNECTED',
    VICARIOUS_MOM_VISIT_CANNOT_BE_WITH_MORE_PARTICIPANT = 'VICARIOUS_MOM_VISIT_CANNOT_BE_WITH_MORE_PARTICIPANT',
    DATE_TIME_NOT_FITS_FOR_ORIGINAL_VISIT = 'DATE_TIME_NOT_FITS_FOR_ORIGINAL_VISIT',
    ORIGINAL_VISIT_IS_NOT_IN_STARTED_STATUS_AT_CONTINUE = 'ORIGINAL_VISIT_IS_NOT_IN_STARTED_STATUS_AT_CONTINUE',

    INVALID_DATE_TIME = 'INVALID_DATE_TIME',
}
